### ISSUE TITLE
Can't launch Server

### ISSUE THREAD

**Issue by synepcice** [Skippeh/parcel-thief#1]
I am sorry , but when trying to launch this server , i get this issue :

[2024-07-12T18:00:03 INFO parcel_server] Server starting...
Error performing logging.
        attempted to log: [2024-07-12T18:00:03 INFO parcel_server] Server starting...
        record: Record { metadata: Metadata { level: Info, target: "parcel_server" }, args: [2024-07-12T18:00:03 INFO parcel_server] Server starting..., module_path: Some(Borrowed("parcel_server")), file: Some(Borrowed("parcel-server\\src\\main.rs")), line: Some(195) }
        logging error: Le chemin d’accès spécifié est introuvable. (os error 3)thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }', C:\Users\runneradmin\.cargo\git\checkouts\pg-embed-a1644eec4c82de4a\655a673\src\postgres.rs:229:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

And the CMD close ...

I think your server is set-up for an Admin called "RunnerAdmin" , But this Admin does not exist on my Computer. Can you edit your software to be more "open-mind" lol ;) 
Thank you very mutch :)

**Comment by amPerl** [comment]
It's nothing to do with "runneradmin", that's not a limitation of any kind, just part of the file path for the error because the release was built on GitHub Actions under that username.

The real issue seems to be this https://github.com/faokunega/pg-embed/issues/9 although that seems to be about an older version, so I'm  not sure why exactly that's showing up now

**Comment by Skippeh** [comment]
A temporary workaround you can use is to run a separate postgresql server. I'll probably have to fork pg-embed to attempt to fix it as the repo seems to be inactive.

**Comment by synepcice** [comment]
Ok , thanks , i'll try it :)

**Comment by synepcice** [comment]
I am sorry, I don't really succeed on making my own PostGreSQL server. I think I will wait for a new release of your emulator fixed with a good Pg-Embed version. Thank you very much for your time and your work.

**Comment by Skippeh** [comment]
Can you try this build? I've replaced pg-embed with an active crate that hopefully works better. Or at the very least gives a more useful error message.

~~https://github.com/Skippeh/parcel-thief/releases/tag/build%2Freplace_pg-embed_dep%2F2024-07-18~~ (use the build below instead)

**Comment by Skippeh** [comment]
I just realised, the logs directory isn't created automatically, oops :D

For now, create a directory called `logs` in the server root (next to the data folder), otherwise logging won't work.

You even wrote it in the OP, but i missed it somehow.

**Comment by Skippeh** [comment]
I fixed the logs directory issue, here's a new build.

https://github.com/Skippeh/parcel-thief/releases/tag/build%2Freplace_pg-embed_dep%2F2024-07-18_2

**Comment by synepcice** [comment]
Hello , I tried the latest build , and this is what happened :

[2024-07-19T08:32:57 INFO parcel_server] Server starting...
[2024-07-19T08:32:57 INFO tracing::span] setup;
[2024-07-19T08:32:57 INFO tracing::span] start;
Error: Failed to setup and launch postgresql server

Caused by:
    Command error: stdout=; stderr=

**Comment by synepcice** [comment]
And this is the Full Log :

![image](https://github.com/user-attachments/assets/52d7b179-e4e8-4b7c-b16f-0785cee2c2e6)

**Comment by Skippeh** [comment]
Can you upload the `start.log` file in the `data/postgresql/data/` directory?

**Comment by synepcice** [comment]
Yes of course :


2024-07-19 08:32:07.052 CEST [7516] FATAL:  database files are incompatible with server
2024-07-19 08:32:07.052 CEST [7516] DETAIL:  The data directory was initialized by PostgreSQL version 10, which is not compatible with this version 16.3.
2024-07-19 08:32:58.312 CEST [1332] FATAL:  database files are incompatible with server
2024-07-19 08:32:58.312 CEST [1332] DETAIL:  The data directory was initialized by PostgreSQL version 10, which is not compatible with this version 16.3.
2024-07-19 08:39:33.111 CEST [4140] FATAL:  database files are incompatible with server
2024-07-19 08:39:33.111 CEST [4140] DETAIL:  The data directory was initialized by PostgreSQL version 10, which is not compatible with this version 16.3.

**Comment by Skippeh** [comment]
It looks like the database needs to be upgraded or deleted. Since it hasn't worked for you yet it's probably easiest to just delete the `data/postgresql/data/` directory and try again. If it doesn't work then please upload the `start.log` file again.

Edit:
I should clarify, the upgrade or deletion is needed because when i switched out pg-embed i also changed to download the newest major version (v15 -> v16), which apparently does not auto upgrade. Makes sense in hindsight since it's a major version change, but i didn't think of it.

It might still not be the solution to your problem though since it wasn't working before either, unless it had to do with the pg-embed crate.

**Comment by synepcice** [comment]
Nice ! It's Working ! Thank You Very Mutch ! You're a Big Boss ;) 

![image](https://github.com/user-attachments/assets/3422b41d-47d9-4f4d-bbd6-6ac67d5867c9)

**Comment by synepcice** [comment]
Issue Corrected :D
